-- Film platformu veritabanı şeması

-- Filmler tablosu
CREATE TABLE IF NOT EXISTS films (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  original_title TEXT,
  imdb_id TEXT,
  imdb_rating DECIMAL(3,1),
  year INTEGER,
  country TEXT,
  description TEXT,
  poster_url TEXT,
  language_types TEXT[] DEFAULT '{}',
  genres TEXT[] DEFAULT '{}',
  view_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active',
  scraped_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Oyuncular tablosu
CREATE TABLE IF NOT EXISTS actors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  bio TEXT,
  avatar_url TEXT,
  film_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Film-oyuncu ilişkisi
CREATE TABLE IF NOT EXISTS film_actors (
  film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
  actor_id BIGINT REFERENCES actors(id) ON DELETE CASCADE,
  character_name TEXT,
  voice_role TEXT,
  PRIMARY KEY (film_id, actor_id)
);

-- Kategoriler
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  type TEXT DEFAULT 'genre',
  film_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Film-kategori ilişkisi
CREATE TABLE IF NOT EXISTS film_categories (
  film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (film_id, category_id)
);

-- Scraping log
CREATE TABLE IF NOT EXISTS scraping_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_url TEXT,
  action TEXT,
  status TEXT,
  message TEXT,
  films_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index'ler
CREATE INDEX IF NOT EXISTS idx_films_slug ON films(slug);
CREATE INDEX IF NOT EXISTS idx_films_year ON films(year);
CREATE INDEX IF NOT EXISTS idx_films_rating ON films(imdb_rating);
CREATE INDEX IF NOT EXISTS idx_films_status ON films(status);
CREATE INDEX IF NOT EXISTS idx_films_created_at ON films(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_films_genres ON films USING GIN(genres);
CREATE INDEX IF NOT EXISTS idx_films_language_types ON films USING GIN(language_types);
CREATE INDEX IF NOT EXISTS idx_films_search ON films USING GIN(to_tsvector('turkish', title || ' ' || COALESCE(original_title, '')));

-- Row Level Security politikaları
ALTER TABLE films ENABLE ROW LEVEL SECURITY;
ALTER TABLE actors ENABLE ROW LEVEL SECURITY;
ALTER TABLE film_actors ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE film_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE scraping_logs ENABLE ROW LEVEL SECURITY;

-- Herkes okuyabilir
CREATE POLICY "Allow public read access" ON films FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON actors FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON film_actors FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON film_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON scraping_logs FOR SELECT USING (true);

-- Insert trigger updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_films_updated_at BEFORE UPDATE ON films
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Varsayılan kategoriler
INSERT INTO categories (name, slug, type) VALUES
('Aksiyon', 'aksiyon', 'genre'),
('Animasyon', 'animasyon', 'genre'),
('Belgesel', 'belgesel', 'genre'),
('Bilim Kurgu', 'bilim-kurgu', 'genre'),
('Biyografi', 'biyografi', 'genre'),
('Dram', 'dram', 'genre'),
('Fantastik', 'fantastik', 'genre'),
('Gerilim', 'gerilim', 'genre'),
('Gizem', 'gizem', 'genre'),
('Komedi', 'komedi', 'genre'),
('Korku', 'korku', 'genre'),
('Macera', 'macera', 'genre'),
('Romantik', 'romantik', 'genre'),
('Savaş', 'savas', 'genre'),
('Suç', 'suc', 'genre'),
('Tarih', 'tarih', 'genre'),
('Western', 'western', 'genre')
ON CONFLICT (slug) DO NOTHING;
